### Site metadata ###
 
site_name: Java Certificado
site_description: Projeto para Gerenciamentos de Certificado Digital
site_url: https://Samuel-Oliveira.github.io/Java_Certificado/

repo_url: https://github.com/Samuel-Oliveira/Java_Certificado
edit_uri: edit/master/docs/docs

### Build settings ###
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

theme:
  name: material
  language: pt-BR
  features:
    - navigation.tracking
    - navigation.expand
    - content.code.annotate

  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Inicio: index.md
  - Exemplos:
      - Certificados A1: tutorial/certificado-a1.md
      - Certificados A3: tutorial/certificado-a3.md
      - Repositórios: tutorial/repositorios.md
      - Certificado por CNPJ/CPF: tutorial/certificado-por-cnpjcpf.md
